###
GET localhost:8080/artists
Accept: application/json
Content-Type: application/json

###

###
POST localhost:8080/artists
Accept: application/json
Content-Type: application/json

{
  "name": "test3",
  "country": "Ukraine"
}

###

PUT localhost:8080/artists/3
Accept: application/json
Content-Type: application/json

{
  "name" : "updatedName",
  "country" : "updCountry"
}


###


